name: CI

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps (Makefile)
        run: make install

      - name: Model tests + coverage
        run: make model-test

      - name: API tests + coverage
        run: make api-test

      - name: Upload reports (coverage, junit)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: |
            reports/**
            reports/html/**
            .coverage
